wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1709051073.45809
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 87
      - 95
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      - 86
      - 87
      - 95
      - 105
      3:
      - 23
      4: 3.11.7
      5: 0.16.3
      6: 4.37.2
      8:
      - 2
      - 5
      9:
        2: llama_index
      13: linux-x86_64
